config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  devise_for :places, controllers: { registrations: 'places/registrations',
                                    sessions: 'places/sessions',
                                    passwords:     'places/passwords' }
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions',
                                    passwords: 'users/passwords'}
  resources :users, only: [:index, :show] do
    member do
      get :user_blogs
    end
  end
  resources :places, only: [:index, :show] do
    collection do
      get 'search'
    end
  end
  resources :favorites, only: [:create, :destroy]
  root 'places#index'
  resources :blogs do
    collection do
      post :confirm
    end
    resources :comments
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :title, presence: true, length: { in: 1..100 }
  validates :content, presence: true, length: { in: 1..1000 }
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :blog_images, dependent: :destroy
  accepts_nested_attributes_for :blog_images, 
                                 allow_destroy: true,
                                 reject_if: :all_blank
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ edit update show destroy ]
  before_action :authenticate_user!, only: %i[ new edit update destroy ]

  def index
    @blogs = Blog.sort_desc.page(params[:page]).per(8)
  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
      5.times { @blog.blog_images.build }
    else
      @blog = Blog.new
      5.times { @blog.blog_images.build }
    end
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if params[:back]
      render :new
    else
      if @blog.save
        redirect_to blogs_path, notice: "素晴らしいです！またごみ拾いの記録をみんなにシェアしてくださいね！"
      else
        render :new, notice: "投稿出来ませんでした"
      end
    end
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  def edit
    if @blog.blog_images.blank?
      5.times { @blog.blog_images.build }
      @blog_images = @blog.blog_images
    elsif @blog.blog_images.count < 5
      (5 - @blog.blog_images.count).times { @blog.blog_images.build }
      @blog_images = @blog.blog_images
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: "編集が完了しました"
    else
      render :edit, notice: "編集出来ませんでした"
    end
  end

  def show
    @blog_images = @blog.blog_images
    @favorite = current_user.favorites.find_by(blog_id: @blog.id) if current_user
    @comments = @blog.comments
    @comment = @blog.comments.build
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "投稿が削除されました"
  end

private
  def blog_params
    params.require(:blog).permit(
                                 :title, 
                                 :content, 
                                 :image, 
                                 :image_cache,
                                 blog_images_attributes: [:id, :blog_id, :image, :image_cache, :_destroy],
                                )
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true, url: choose_new_or_edit) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
    <h2><%= blog.errors.count %> 件のエラーが発生しました</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <strong><%= form.label :メイン画像 %></strong>
      <p>（一覧画面に表示される画像です）</p>
      <p><%= image_tag(@blog.image.url, class: "blog_main_image") if @blog.image && @blog.image.url %></p>

      <%= form.file_field :image %>

      <%= form.hidden_field :image_cache %>
    </div>

    <div class="col-md-6">
      <div class="field">
        <strong><%= form.label :タイトル %></strong>
        <p><%= form.text_field :title, size: "30x5" %></p>
      </div>

      <div class="field">
        <strong><%= form.label :内容 %></strong>
        <p><%= form.text_area :content, size: "30x10" %></p>
      </div>
    </div>
  </div>

  <p>写真は５枚まで投稿できます</p>
  <%= form.fields_for :blog_images do |image| %>
    <div class="field">
      <%= image_tag(image.object.image.url, class: "blog_images") if image.object.image && image.object.image.url %>
      <%= image.hidden_field :image_cache %>
      <%= image.file_field :image if image.object.new_record? %>
    </div>


    <% unless image.object.new_record? %>
      <div>
        <p>画像を削除<%= image.check_box :_destroy, data: { confirm: '削除してよろしいですか' }%></p>
      </div>
    <% end %>
  <% end %>

  <div class="blog_links">
    <%= form.submit class: "btn btn-success btn-block" %>
  </div>
<% end %>

app/views/blogs/confirm.html.erb
<h3>投稿確認画面</3>
<h5>以下の内容でよろしいですか？</h5>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>

  <div class="row">
    <div class="col-12 col-md-6">
      <%= image_tag(@blog.image.url, class: "confirm_main_image") if @blog.image && @blog.image.url %>
      <%= form.hidden_field :image_cache %>
      <%= form.hidden_field :title %>
      <%= form.hidden_field :content %>
    </div>

    <div class="col-12 col-md-6">
      <%= form.submit  "みんなにシェア", class: "btn btn-warning" %>
      <%= form.submit "戻る", name: 'back', class: "btn btn-outline-info" %>
      <div class="card">
        <div class="card-body">
          <strong>タイトル</strong>
          <p><%= @blog.title %></p>
          <strong>本文</strong>
          <p><%= @blog.content %></p>
        </div>
      </div>
    </div>
  </div>

  <% @blog.blog_images.each do |blog_image| %>
    <%= image_tag(blog_image.image.url, class: "confirm_sub_images") if blog_image.image && blog_image.image.url %>
  <% end %>

  <%= form.fields_for :blog_images do |blog_image| %>
    <%= blog_image.hidden_field :image_cache %>
  <% end %>
<% end %>

app/views/blogs/edit.html.erb
<h1>ごみ拾い記録編集</h1>

<%= render 'form', blog: @blog %>

<%= link_to '投稿一覧へ戻る', blogs_path %>

app/views/blogs/index.html.erb
<h1>みんなのごみ拾い記録一覧</h1>
<br>
<%= link_to '新しく記録を投稿する', new_blog_path, class: "btn btn-outline-warning" %>

<% @blogs.each do |blog| %>
  <div class="card mb-3">
    <div class="row no-gutters">
      <div class="col-md-4">
        <% if blog.image.url.present? %>
          <%= (image_tag blog.image.url, class: "index_blogs_image") %>
        <% else %>
          <i class="fas fa-camera fa-5x"></i>
          <p>NO IMAGE<p>
        <% end %>
      </div>
      <div class="col-md-8">
        <div class="card-body user_blogs_content">
          <p><i class="fas fa-user-alt"></i><%= blog.user.name %></p>
          <h5 class="card-title"><%= blog.title %></h5>
          <p class="card-text"><%= blog.created_at.strftime("%Y-%m-%d %H:%M") %></p>
          <p class="card-text"><%= blog.content %></p>
        </div>
        <% if blog.favorite_users.count >= 1 %> 
          <i class="fas fa-heart fa-lg heart"></i>
          <%= blog.favorite_users.count %>
        <% elsif blog.favorite_users.count == 0 %>
          <i class="far fa-heart fa-lg heart"></i>
        <% end %>
        <% if blog.blog_images.any? %>
          <i class="fas fa-camera"></i><%= blog.blog_images.count %>
        <% end %>
        <%= link_to '詳細', blog_path(blog), class: "btn btn-outline-success" %>
        <% if current_user == blog.user %>
          <%= link_to '編集', edit_blog_path(blog), class: "btn btn-outline-warning" %>
          <%= link_to '削除', blog, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: "btn btn-outline-warning" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<%= paginate @blogs %>

app/views/blogs/new.html.erb
<h2>ごみ拾い記録を投稿</h2>

<%= render 'form', blog: @blog %>

<%= link_to '投稿一覧へ戻る', blogs_path %>

app/views/blogs/show.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="blog_user_info">
      <i class="fas fa-user-alt"></i><%= "#{@blog.user.name}さんのごみ拾い記録" %>
    </div>
    <div class="blog_user_info">
      <%= image_tag(@blog.user.image.url, class: "profile_image") if @blog.user.image.present? %>
    </div>
    <div class="blog_user_info">
      <%= link_to "#{@blog.user.name}さんのページ", user_path(@blog.user.id), class: "btn btn-outline-success" %>
    </div>
  </div>
  
  <div class="col-md-9">
    <div class="like" >
      <% if @favorite.present? %>
        <%= link_to favorite_path(id: @favorite.id), method: :delete, class: "unlike_btn" do %>
          <i class="fas fa-heart fa-lg heart"></i>
        <% end %>
        <%= @blog.favorite_users.count %>
      <% else %>
        <%= link_to favorites_path(blog_id: @blog.id), method: :post, class: "like_btn" do %>
          <i class="far fa-heart fa-lg heart"></i>
        <% end %>
      <% end %>
    </div>  
    
    <div class="blog_content">
      <strong><%= @blog.title %></strong>
    </div>

    <p><%= @blog.created_at.strftime("%Y-%m-%d %H:%M") %></p>
    
    <% if @blog.image.url.present?%>
      <div class="blog_main_image">
        <%= (image_tag @blog.image.url, class: "user_blogs_image") %>
      </div>
    <% end %>

    <p class="blog_content"><%= @blog.content %></p>

    <% if @blog_images.any? %>
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= image_tag(@blog_images.first.image.url, class: "d-block w-100") %>
          </div>

          <% @blog_images[1..].each do |blog_image| %>
            <div class="carousel-item">
              <%= image_tag(blog_image.image.url, class: "d-block w-100") %>
            </div>
          <% end %>

          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    <% elsif current_user == @blog.user && @blog_images.blank? %>
      <h3>写真はあと５枚投稿出来ます</h3>
    <% end %>

    <% if current_user == @blog.user %>
      <div class="blog_links">
        <%= link_to '編集', edit_blog_path(@blog), class: "btn btn-outline-secondary btn-block" %>
        <%= link_to '削除', blog_path(@blog), method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: "btn btn-outline-danger btn-block" %>
      </div>
    <% end %>
    
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, blog: @blog } %>
    </div>

    <%= render partial: 'comments/form', locals: { comment: @comment, blog: @blog } %>
    
    <div class="blog_links">
      <%= link_to '一覧画面に戻る', blogs_path, class: "btn btn-success btn-block" %>
    </div>
  </div>
</div>