config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  devise_for :places, controllers: { registrations: 'places/registrations',
                                    sessions: 'places/sessions',
                                    passwords:     'places/passwords' }
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions',
                                    passwords: 'users/passwords'}
  resources :users, only: [:index, :show] do
    member do
      get :user_blogs
    end
  end
  resources :places, only: [:index, :show] do
    collection do
      get 'search'
    end
  end
  resources :favorites, only: [:create, :destroy]
  root 'places#index'
  resources :blogs do
    collection do
      post :confirm
    end
    resources :comments
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :blogs
  validates :name, presence: true
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_update_path_for(resource)
    user_path(current_user.id)
  end

  
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

def after_sign_in_path_for(resource)
  user_path(current_user.id)
end 

def after_sign_out_path_for(resource)
  new_user_session_path
end 

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def user_blogs
    @user = User.find(params[:id])
    @blogs = @user.blogs.sort_desc.page(params[:page]).per(8)
  end
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<ul class="row">
  <li class="col-md-7">
    <h2 class="user_info"><%= @user.name %>さんのページ </h2>
    <h4 class="user_info"><%= @user.email %></h3>
    <% if @user.image.url.present? %>
      <%= (image_tag @user.image.url, class: "user_profle_image") %>
    <% else %>
      <i class="fas fa-camera fa-5x"></i>
      <p>NO IMAGE<p>
    <% end %>
    <% if current_user == @user %>
      <div class="user_info">
        <%= link_to "アカウント情報の編集", edit_user_registration_path, class: "btn btn-info" %>
      </div>
    <% end %>
  </li>
  <li class="col-md-5">
    <div class="user_links">
      <%= link_to "ごみ回収place一覧", places_path, class: "user_link" %>
    </div>
    <div class="user_links">
      <%= link_to "#{@user.name}さんのごみ拾い記録",  user_blogs_user_path, class: "user_link" %>
    </div>
    <div class="user_links">
      <%= link_to "みんなのごみ拾い記録", blogs_path, class: "user_link" %>
    </div>
    <div class="user_links">
      <%= link_to "参加予定イベント一覧", "#", class: "user_link" %>
    </div>
    <div class="user_links">
      <%= link_to "イベント一覧", "#", class: "user_link" %>
    </div>
    <div class="user_links">
      <%= link_to "友達一覧", "#", class: "user_link" %>
    </div>
  </li>
</ul>

app/views/users/user_blogs.html.erb
<h2><%= @user.name %>さんのごみ拾い記録一覧</h2>
<br>
<%= link_to '新しく記録を投稿する', new_blog_path, class: "btn btn-outline-warning" %>

<% @blogs.each do |blog| %>
  <div class="card mb-3">
    <div class="row no-gutters">
      <div class="col-md-4">
        <%= (image_tag blog.image.url, class: "index_blogs_image") if blog.image.url.present? %>
      </div>
      <div class="col-md-8">
        <div class="card-body user_blogs_content">
          <h5 class="card-title"><%= blog.title %></h5>
          <p class="card-text"><%= blog.created_at.strftime("%Y-%m-%d %H:%M") %></p>
          <p class="card-text"><%= blog.content %></p>
        </div>
        <%= link_to '詳細', blog_path(blog), class: "btn btn-outline-success" %>
        <% if current_user == blog.user %>
          <%= link_to '編集', edit_blog_path(blog), class: "btn btn-outline-warning" %>
          <%= link_to '削除', blog, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: "btn btn-outline-warning" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<%= paginate @blogs %>