config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  devise_for :places, controllers: { registrations: 'places/registrations',
                                    sessions: 'places/sessions',
                                    passwords:     'places/passwords' }
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions',
                                    passwords: 'users/passwords'}
  resources :users, only: [:index, :show] do
    member do
      get :user_blogs
    end
  end
  resources :places, only: [:index, :show] do
    collection do
      get 'search'
    end
  end
  resources :favorites, only: [:create, :destroy]
  root 'places#index'
  resources :blogs do
    collection do
      post :confirm
    end
    resources :comments
  end
end

app/models/place.rb
class Place < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :name, presence: true
  validates :address, presence: true
  validates :description, length: { in: 1..100 }
  has_one :rule, dependent: :destroy, autosave: true
  accepts_nested_attributes_for :rule, 
                                allow_destroy: true,
                                reject_if: :all_blank
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/places/confirmations_controller.rb
# frozen_string_literal: true

class Places::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/places/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Places::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/places/passwords_controller.rb
# frozen_string_literal: true

class Places::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/places/registrations_controller.rb
# frozen_string_literal: true

class Places::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
    # super do |resource|
    #   resource.build_rule
    # end
  end

  # POST /resource
  def create
    super
    resource.create_rule if resource.persisted?
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def after_sign_up_path_for(resource)
    place_path(current_place.id)
  end
  
  def after_update_path_for(resource)
    place_path(current_place.id)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/places/sessions_controller.rb
# frozen_string_literal: true

class Places::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_in_path_for(resource)
    place_path(current_place.id)
  end 
  
  def after_sign_out_path_for(resource)
    new_place_registration_path
  end 

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/places/unlocks_controller.rb
# frozen_string_literal: true

class Places::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_q, only: [:index, :search]
  def index
    @places = Place.sort_desc.page(params[:page]).per(8)
  end

  def show
    @place = Place.find(params[:id])
    @rule = @place.rule
  end

  def search
    @results = @q.result
  end
  private

  def set_q
    @q = Place.ransack(params[:q])
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/index.html.erb
<h2>ごみ回収場所一覧</h2>

<div class="row">
  <div class="col-12 col-md-3 search_forms">
    <%= search_form_for @q, url: search_places_path do |f| %>
      <p><i class="fas fa-search"></i><%= f.label :address_cont, '住所' %></p>
      <p><%= f.search_field :address_cont, size: "25x5" %></p>
      <br>
      <p><i class="fas fa-search"></i><%= f.label :name_cont, '場所の名称・店名' %></p>
      <p><%= f.search_field :name_cont, size: "25x5" %></p>
      <br>
      <%= f.submit '検索', class: "btn btn-outline-info btn-block" %>
    <% end %>
  </div>
  <div class="col-12 col-md-9 place_index_card">
    <% @places.each do |place| %>
      <div class="card mb-3" style="max-width: 800px;">
        <div class="row no-gutters">
          <div class="col-md-4">
            <% if place.image.url.present? %>
              <%= (image_tag place.image.url, class: "index_place_image") %>
            <% else %>
              <i class="fas fa-camera fa-5x"></i>
              <p>NO IMAGE<p>
            <% end %>
          </div>
          <div class="col-md-6">
            <div class="card-body">
              <h5 class="card-title"><i class="fas fa-home"></i><%= place.name %></h5>
              <p class="card-text"><i class="fas fa-map-marker-alt"></i><%= place.address %></p>
              <p class="card-text"><%= place.description %></p>
            </div>
          </div>
          <div class="col-md-2 place_index_show_btn">
            <p class="card-link"><%= link_to '詳細', place_path(place.id), class: "btn btn-success" %></P>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= paginate @places %>

app/views/places/search.html.erb
<h2>検索結果</h2>
<%= link_to "place一覧に戻る", places_path, class: "btn btn-outline-success" %>
<div class="col-sm-9 col-md-9 place_index_card">
  <% @results.each do |place| %> 
    <div class="card mb-3" style="max-width: 950px;">
      <div class="row no-gutters">
        <div class="col-md-4">
          <% if place.image.url.present? %>
            <%= image_tag place.image.url , class: "index_place_image"%>
          <% else %>
            <i class="fas fa-camera fa-5x"></i>
            <p>NO IMAGE<p>
          <% end %>
        </div>
        <div class="col-md-6">
          <div class="card-body">
            <h5 class="card-title"><i class="fas fa-home"></i><%= place.name %></h5>
            <p class="card-text"><i class="fas fa-map-marker-alt"></i><%= place.address %></p>
            <p class="card-text"><%= place.description %></p>
          </div>
        </div>
        <div class="col-md-2 place_index_show_btn">
          <p class="card-link"><%= link_to '詳細', place_path(place.id), class: "btn btn-success" %></P>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/places/show.html.erb
<div class="row">
  <div class="col-md-7">
    <h2 class="place_info"><%= @place.name %></h2>
    <% if @place.image.url.present? %>
      <%= (image_tag @place.image.url, class: "index_place_image") %>
    <% else %>
      <i class="fas fa-camera fa-5x"></i>
      <p>NO IMAGE<p>
    <% end %>
    <p><%= @place.description %></p>
    <% if current_place == @place %>
      <h4 class="place_info"><%= @place.email %></h4>
      <div class="place_info">
        <%= link_to "アカウント情報の編集", edit_place_registration_path(@place.id), class: "btn btn-info" %>
      </div>
    <% end %>

    <% if current_place == @place %>
      <h5 class="rules_info">ごみ持ち込みルールは編集画面より記載をお願いします</h5>
    <% end %>
    <div class="place_rules">
      <% if @rule.start_at.present? && @rule.start_at.strftime('%H:%M') != '00:00' %>
        <p>受付開始時間：<%= @rule.start_at.strftime('%H:%M') %></p>
      <% else %>
        <p>受付開始時間：特に指定なし</p>
      <% end %>

      <% if @rule.end_at.present? && @rule.end_at.strftime('%H:%M') != '00:00' %>
        <p>受付終了時間：<%= @rule.end_at.strftime('%H:%M') %></p>
      <% else %>
        <p>受付終了時間：特に指定なし</p>
      <% end %>

      <% if @rule.separation.present? %>
        <p>分別方法：<%= @rule.separation %></p>
      <% else %>
        <p>分別方法：特に指定なし</p>
      <% end %>

      <% if @rule.amount.present? %>
          <p>ごみの量：<%= @rule.amount %></p>
      <% else %>
        <p>ごみの量：特に指定なし</p>
      <% end %>

      <% unless @rule.comment.blank? %>
        <p>注意事項：<%= @rule.comment %></p>
      <% else %>
        <p>注意事項：特に指定なし</p>
      <% end %>
    </div>
  </div>

  <div class="col-md-5 place_show_links">
    <div class="place_links">
      <%= link_to "ごみ回収place一覧", places_path, class: "place_link" %>
    </div>
    <div class="place_links">
      <%= link_to "みんなのごみ拾い記録", blogs_path, class: "place_link" %>
    </div>
    <div class="place_links">
      <%= link_to "イベント一覧", "#", class: "place_link" %>
    </div>

    <% if current_place == @place %>
      <div class="place_links">
        <%= link_to "#{@place.name}さん参加予定イベント一覧", "#", class: "place_link" %>
      </div>
      <div class="place_links">
        <%= link_to "#{@place.name}さん友達一覧", "#", class: "place_link" %>
      </div>
    <% end %>
  </div>
</div>