config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  devise_for :places, controllers: { registrations: 'places/registrations',
                                    sessions: 'places/sessions',
                                    passwords:     'places/passwords' }
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions',
                                    passwords: 'users/passwords'}
  resources :users, only: [:index, :show] do
    member do
      get :user_blogs
    end
  end
  resources :places, only: [:index, :show] do
    collection do
      get 'search'
    end
  end
  resources :favorites, only: [:create, :destroy]
  root 'places#index'
  resources :blogs do
    collection do
      post :confirm
    end
    resources :comments
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PickingUpGarbage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
  <div class="wrapper">
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <%= link_to "NO MORE garbo", places_path, class: "nav-link no_more_garbo" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          LINK
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "マイページ", user_path(current_user.id), class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ブログ投稿一覧", blogs_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ごみ回収place一覧", places_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% elsif place_signed_in? %>
              <li class="nav-item">
                <%= link_to "場所・お店のページ", place_path(current_place.id), class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ブログ投稿一覧", blogs_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ごみ回収place一覧", places_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_place_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "ごみ拾いユーザー新規登録", new_user_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ごみ拾いユーザーログイン", new_user_session_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "場所・お店アカウント登録", new_place_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "場所・お店ログイン", new_place_session_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
    <% end %>
    
    <div class="container">
      <%= yield %>
    </div>

    </div>
    <footer class="footer">
      <p>no more garbo by TonbiNeko</p>
      <p>DIC graduation app</p>
    </footer>

  </body>
</html>